config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :crud_operations
  
  resources :users do
    resources :tweets, only: [:index]
  end

  resources :tweets

  get 'roles'      => 'roles#index'
  get   'roles/:id'  => 'roles#show'
  put   'roles/:id'  => 'roles#edit'
  patch 'roles/:id'  => 'roles#edit'

  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  scope '/api' do
    scope '/v1' do
        resources :users, format: 'json'
        resources :users, format: 'json'
    end
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

  belongs_to :user
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  prepend_before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    if params[:user_id].nil?
      @tweets = Tweet.all
    else
      @tweets = User.find(params[:user_id]).tweets
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    @tweet.user = current_user
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        flash[:success] = 'Tweet was successfully created.'
        format.html { redirect_to user_tweets_url(@tweet.user) }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        flash[:success] = 'Tweet was successfully updated.'
        format.html { redirect_to user_tweets_url(@tweet.user) }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      flash[:success] = 'Tweet was successfully destroyed.'
      format.html { redirect_to user_tweets_url(@tweet.user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
      self.obj = @tweet
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:msg, :user_id)
    end
end

app/views/tweets/_form.html.erb
<%= form_for @tweet do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :msg %><br>
    <%= f.text_field :msg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', :back %>

app/views/tweets/index.html.erb
<h1>Listing Tweets</h1>


<% if @tweets.count == 0 %>

  <h2>This user has no tweets</h2>

<% else %>
  <table>
    <thead>
      <tr>
        <th>Msg</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tweets.each do |tweet| %>
        <tr>
          <td><%= tweet.msg %></td>
          <td><%= tweet.user_id %></td>
          <td><%= link_to 'Show', tweet %></td>
          <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/tweets/show.html.erb
<p>
  <strong>Msg:</strong>
  <%= @tweet.msg %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', :back %>