config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :crud_operations
  
  resources :users do
    resources :tweets, only: [:index]
  end

  resources :tweets

  get 'roles'      => 'roles#index'
  get   'roles/:id'  => 'roles#show'
  put   'roles/:id'  => 'roles#edit'
  patch 'roles/:id'  => 'roles#edit'

  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  scope '/api' do
    scope '/v1' do
        resources :users, format: 'json'
        resources :users, format: 'json'
    end
  end

end

app/models/crud_operation.rb
class CrudOperation < ActiveRecord::Base
  belongs_to :role

  @@default_controller = 'default'

  def self.default_controller
    @@default_controller
  end

end

app/controllers/crud_operations_controller.rb
class CrudOperationsController < ApplicationController
  before_action :set_crud_operation, only: [:show, :edit, :update, :destroy]

  # GET /crud_operations
  # GET /crud_operations.json
  def index
    @crud_operations = CrudOperation.all
  end

  # GET /crud_operations/1
  # GET /crud_operations/1.json
  def show
  end

  # GET /crud_operations/new
  def new
    @crud_operation = CrudOperation.new
  end

  # GET /crud_operations/1/edit
  def edit
  end

  # POST /crud_operations
  # POST /crud_operations.json
  def create
    @crud_operation = CrudOperation.new(crud_operation_params)

    respond_to do |format|
      if @crud_operation.save
        format.html { redirect_to @crud_operation, notice: 'Crud operation was successfully created.' }
        format.json { render :show, status: :created, location: @crud_operation }
      else
        format.html { render :new }
        format.json { render json: @crud_operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crud_operations/1
  # PATCH/PUT /crud_operations/1.json
  def update
    respond_to do |format|
      if @crud_operation.update(crud_operation_params)
        format.html { redirect_to @crud_operation, notice: 'Crud operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @crud_operation }
      else
        format.html { render :edit }
        format.json { render json: @crud_operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crud_operations/1
  # DELETE /crud_operations/1.json
  def destroy
    @crud_operation.destroy
    respond_to do |format|
      format.html { redirect_to crud_operations_url, notice: 'Crud operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crud_operation
      @crud_operation = CrudOperation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crud_operation_params
      params.require(:crud_operation).permit(:crud_op, :role_id, :eval_exp)
    end
end

app/views/crud_operations/_form.html.erb
<%= form_for(@crud_operation) do |f| %>
  <% if @crud_operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crud_operation.errors.count, "error") %> prohibited this crud_operation from being saved:</h2>

      <ul>
      <% @crud_operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :crud_op %><br>
    <%= f.text_field :crud_op %>
  </div>
  <div class="field">
    <%= f.label :role_id %><br>
    <%= f.number_field :role_id %>
  </div>
  <div class="field">
    <%= f.label :eval_exp %><br>
    <%= f.text_field :eval_exp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crud_operations/edit.html.erb
<h1>Editing Crud Operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @crud_operation %> |
<%= link_to 'Back', crud_operations_path %>

app/views/crud_operations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Crud Operations</h1>

<table>
  <thead>
    <tr>
      <th>Crud op</th>
      <th>Role</th>
      <th>Eval exp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crud_operations.each do |crud_operation| %>
      <tr>
        <td><%= crud_operation.crud_op %></td>
        <td><%= crud_operation.role_id %></td>
        <td><%= crud_operation.eval_exp %></td>
        <td><%= link_to 'Show', crud_operation %></td>
        <td><%= link_to 'Edit', edit_crud_operation_path(crud_operation) %></td>
        <td><%= link_to 'Destroy', crud_operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crud operation', new_crud_operation_path %>

app/views/crud_operations/new.html.erb
<h1>New Crud Operation</h1>

<%= render 'form' %>

<%= link_to 'Back', crud_operations_path %>

app/views/crud_operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Crud op:</strong>
  <%= @crud_operation.crud_op %>
</p>

<p>
  <strong>Role:</strong>
  <%= @crud_operation.role_id %>
</p>

<p>
  <strong>Eval exp:</strong>
  <%= @crud_operation.eval_exp %>
</p>

<%= link_to 'Edit', edit_crud_operation_path(@crud_operation) %> |
<%= link_to 'Back', crud_operations_path %>