config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :crud_operations
  
  resources :users do
    resources :tweets, only: [:index]
  end

  resources :tweets

  get 'roles'      => 'roles#index'
  get   'roles/:id'  => 'roles#show'
  put   'roles/:id'  => 'roles#edit'
  patch 'roles/:id'  => 'roles#edit'

  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'signup'  => 'users#new'

  scope '/api' do
    scope '/v1' do
        resources :users, format: 'json'
        resources :users, format: 'json'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterKnockoffApiWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">

    <h1> Welcome the the Twitter Knockoff Application</h1>

    <% if @current_user.nil? %>
        <%= link_to "Login", { controller: "sessions", action: "new" }%>
        <br>
        <%= link_to "Create Account", new_user_path %>
    <% else %>
        <p>Logged as <%= @current_user.username %> <%= @current_user.role == Role.admin ? '(admin)' : '' %> </p>
        <%= link_to "Logout", logout_path, method: :delete %>
    <% end %>


    <% flash.each do |type, msg| %>
        <p id=notice class="bg-<%= type %>"><%= msg %></p>
    <% end %>

    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
    <%= debug(@output) if Rails.env.development? and !@output.nil? %>


      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </div>
</body>
</html>